### ISSUE TITLE
documentation needed

### ISSUE THREAD

**Issue by magg** [google/tarpc#102]
Hello

Could you provide documentation on how to write the .proto files in rust code...

I'm trying to connect a rust client with a java server, so far I can't seem to reproduce the my proto file in rust

thanks

**Comment by tikue** [comment]
Tarpc doesn't use protocol buffers. Instead RPC arguments need to implement `serde::Serialize` and `serde::Deserialize`. I do know there are a few different projects floating around that add rust support to protobufs but I don't have a link handy!
