### ISSUE TITLE
Return a server future so users can decide how to run their server

### ISSUE THREAD

**Issue by shaladdle** [google/tarpc#104]
cc @tikue

Currently, we force users to call `server.listen(reactor_handle, addr);`. Forcing users to use a handle is a little opinionated, since users of the futures API might want to be able to explicitly control how they run their server on their reactors.

This would change `FutureService` to expose a `bind` call, which would either return the bound address and a future which encapsulates the server itself, or just a future which exposes a `local_addr` method. Then users can choose how to run this future on their reactor(s).

**Comment by tikue** [comment]
Closed by #199. The users now have control over how they run their server future.
