### ISSUE TITLE
[Feature] target rustc stable

### ISSUE THREAD

**Issue by JohnLih** [google/tarpc#131]
Compiling tarpc-plugins v0.1.0 (https://github.com/google/tarpc#f9ff2c4e)
error[E0554]: #[feature] may not be used on the stable release channel
 --> ~/.cargo/git/checkouts/tarpc-87655b19c07c6cd1/f9ff2c4/src/plugins/src/lib.rs:1:1
  |
1 | #![feature(plugin_registrar, rustc_private)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `tarpc-plugins`.

rustc version :  rustc 1.15.1 (021bd294c 2017-02-08)
cargo version : cargo 0.16.0-nightly (6e0c18c 2017-01-27)
OS version : macOS Sierra 10.12.3

**Comment by tikue** [comment]
Sorry about that! tarpc currently only works on nightly. We should probably have a better disclaimer in the readme.

I expect tarpc will work on stable sometime this year; we're basically waiting on the forthcoming procedural macros 2.0 overhaul.

**Comment by tikue** [comment]
I don't believe so, because the subset being stabilized does not allow you to reexport a proc macro from another crate. :( I'm working on some pretty big updates for async/await and futures 0.3, though. That might land in the next few weeks.

**Comment by chefsalim** [comment]
Wondering if there is any update on this?

**Comment by tikue** [comment]
Given that #199 uses the std futures API and async/await, I think it's safe to say targeting stable is out of reach for the foreseeable future.

**Comment by tikue** [comment]
#199 does remove the use of rustc plugins (!!) so we're definitely moving closer to this. However, I still don't think futures/async/await will be stable very soon.

**Comment by mark-i-m** [comment]
I'm not sure about that. A lot of work is going into the edition 2018 stuff, so almost everything else is paused, but async/await and networking are high priority, and I suspect that they will resume work on them pretty soon after the edition ships. My guess is that they stabilize some time next year.

**Comment by tikue** [comment]
Yeah :) whenever they're stable, I believe I can target stable.

**Comment by vorot93** [comment]
See #242
