### ISSUE TITLE
warning: use of deprecated item: renamed to `send`

### ISSUE THREAD

**Issue by nooberfsh** [google/tarpc#132]
> `warning: use of deprecated item: renamed to `send`
  --> src\main.rs:23:1
   |
23 |   service! {
   |  _^ starting here...
24 | |     rpc simplify(src: String, target: String) -> String;
25 | | }
   | |_^ ...ending here
   |
   = note: #[warn(deprecated)] on by default
   = note: this error originates in a macro outside of the current crate`

i use the code in the example on master branch

**Comment by tikue** [comment]
Looks like a new version of the futures crate was released today!

**Comment by jonhoo** [comment]
This is littering all my builds right now, especially when running tests when they're all printed *twice* :( Is just moving to `send` a sufficient intermediate fix, or do you want to do a larger change?

**Comment by tikue** [comment]
The fix is in #129. Let me see if I can't negotiate with @shaladdle on a review.

**Comment by jonhoo** [comment]
#129 just became a catch-all of all sorts of things, didn't it? :p

**Comment by tikue** [comment]
Yeah. PRs are hard.
