### ISSUE TITLE
Feature Request: Support Serde 1.0

### ISSUE THREAD

**Issue by fintelia** [google/tarpc#146]
Serde 1.0 [was recently released](https://users.rust-lang.org/t/serde-and-serde-json-1-0-0-released/10466). It would be nice if tarpc support this new version.

**Comment by tikue** [comment]
Waiting for bincode.

**Comment by fintelia** [comment]
Based on [this](https://github.com/TyOverby/bincode/pull/149) pull request, it looks like bincode has support on master but are waiting to publish until they can convert to zero copy.

**Comment by tikue** [comment]
Ah cool, yeah I made the changes the other day, so I'll have a PR ready the moment they do a release. Feel free to ping me here if you notice before me that a new version of bincode was released.

**Comment by fintelia** [comment]
@tikue bincode just released 0.8.0 which includes support for serde 1.0

**Comment by tikue** [comment]
Thanks! I'll try to get to it today.

**Comment by tikue** [comment]
v0.8.0 now on crates.io.
