### ISSUE TITLE
Abstract service over AsyncRead and AsyncWrite.

### ISSUE THREAD

**Issue by kkimdev** [google/tarpc#155]
Please refer to #39 for the prior discussion.

For example, https://github.com/kmcallister/urpc abstracts service over `Read + Write` trait.  The benefit of doing this includes:
1. Being able to plug-in any transport layer easily, stdin/out, IPC, UDP+KCP, Websocket, etc... #38
2. Multiple services on one server/port. #153
3. Supporting event-notification pattern #39

Considerations:
- I don't know if this will affect API ergonomics, but I suspect that it will be trivial to provide a helper function, if it affects.
- Simply using multiple services for 2 and 3 might not be ideal as we won't have the holistic view of the server state and make it harder to support features like rate-limiting, load-balancing, etc.  But Using multiple services won't introduce additional complexity to tarpc so I think that's fine as a mid-term solution.

@tikue do you have any additional comment?

**Comment by tikue** [comment]
I don't think abstracting over read/write inherently enables multiplexing services on a single port. Do you agree with that?

**Comment by kkimdev** [comment]
Yeah it does not directly enable that.  What I was thinking is that a user needs to provide a multiplexed component so that one TCP connection can be shared as multiple AsyncRead and AsyncWrite, conceptually something like this:

```Rust
fn multiplex_read_2(x: AsyncRead) -> (/*R1*/ impl AsyncRead, /*R2*/ impl AsyncRead) {/* ... */}
fn multiplex_write_2(x: AsyncWrite) -> (/*W1*/ impl AsyncWrite, /*W2*/ impl AsyncWrite) {/* ... */}
```

So that writing to `W1` should be received by `R1` and the same for `W2` and `R2`.  And use each pair to construct independent services.

**Comment by tikue** [comment]
The latest version is now transport agnostic! It's not generic over `AsyncRead/AsyncWrite`, but it is generic over `Stream<Request> + Sink<Response>`.
