### ISSUE TITLE
Ability to check last request error or connection status

### ISSUE THREAD

**Issue by Boscop** [google/tarpc#160]
Is it possible to get the error of the last request (or `None`) or check the connection status of a client.
Or what is the recommended way to implement auto reconnect?

**Comment by tikue** [comment]
Auto-reconnect is another feature we've wanted to implement but haven't had time to. I've looked in the past to see if tokio had a cookbook for idioms like this and don't remember finding anything exactly like I was thinking. There's [this SO answer](https://stackoverflow.com/questions/42107668/asynchronously-reconnecting-a-client-to-a-server-in-an-infinite-loop) but it's not quite the same. Carl has a [placeholder](https://crates.io/crates/tokio-reconnect/0.0.0) on crates.io for tokio-reconnect...

**Comment by tikue** [comment]
Let's move further discussion to https://github.com/google/tarpc/issues/118.
