### ISSUE TITLE
Call to rpc doesn't get a reply on specific port

### ISSUE THREAD

**Issue by indefini** [google/tarpc#165]
I made a server and a client with SyncService on port 10000 (from an example).
The client is able to connect and the call to the rpc sometimes works but usually I never get a reply from the server. For example if I make a loop calling the rpc method it is only called 1 or 3 times.

But I tried to change the port to 1111 and it works without any problem.
I didn't investigate why, but I guess this deserves an issue.

**Comment by tikue** [comment]
Thanks for the report! I'll try to investigate this weekend.

**Comment by tikue** [comment]
Hi! Any luck reproducing this?

**Comment by indefini** [comment]
oh sorry I didn't see your request about the code. I will publish it on github when I can :)

**Comment by indefini** [comment]
Well It's working now and I can't reproduce it... If I can reproduce it in the future I will reopen the issue if that's ok.

**Comment by tikue** [comment]
Sure, thanks for letting me know!
