### ISSUE TITLE
How can I use `?` for error handling?

### ISSUE THREAD

**Issue by Boscop** [google/tarpc#169]
How can I use `?` for error handling?
```rust
	loop {
		if let Some(ref c) = client {
			if let Err(_) = (|| -> Result<(), Error<()>> {
				if let Some(update) = c.check_for_update(cookies.clone())? {
					let r = update::install_update(&update);
				}
				// ...
				Ok(())
			})() {
				client = None;
			}
		} else {
			if let Ok(c) = connect() {
				client = Some(c);
			}
		}
		sleep(Duration::from_secs(1));
	}
```

error: src\main.rs:79: the trait bound `comm::Error<()>: std::convert::From<tarpc::Error<comm::Error<()>>>` is not satisfied

**Comment by tikue** [comment]
I assume `comm::Error<()>` is an error generated by your application? Typically you'd use something like [error-chain](https://crates.io/crates/error-chain) that encodes the various types of errors your application can encounter. I'm not sure if this is tarpc specific, but let me know if I'm misunderstanding!

**Comment by Boscop** [comment]
Ah right, I had to use `Result<(), tarpc::Error<Error<()>>>`...
