### ISSUE TITLE
Clients don't detect short server failures?

### ISSUE THREAD

**Issue by mark-i-m** [google/tarpc#174]
Is there a way to set the sync clients to have a timeout if they don't receive a response? It seems that if a server fails and comes back up very quickly, the clients don't notice and keep waiting for a response they will never get...

**Comment by tikue** [comment]
This is a missing feature on the sync client. You can use the future client to achieve this. I don't think I have time to add this super soon, but pull requests would be accepted.

**Comment by tikue** [comment]
It'd probably require a new dependency, probably on [`tokio_timer`](https://docs.rs/tokio-timer/0.1.2/tokio_timer/). And then the rpc fns would need to have an overload that supports a timeout, like `rpc foo_with_options(call_options: CallOptions, request: Request)` (where `CallOptions` impls a method that sets a timeout). This kind of ties into other discussions about metadata carried in requests (#152). There are really two kinds of contextual data contained in a request: data used to control how the request is handled (such as timeouts, retries, etc.), and data that's sent alongside the request to the server.

**Comment by tikue** [comment]
The latest release supports deadlines.
