### ISSUE TITLE
"No connection could be made because the target machine actively refused it."

### ISSUE THREAD

**Issue by Boscop** [google/tarpc#176]
When I run my tarpc client on the same (windows) laptop as my tarpc server, it always fails to connect, also on every retry:
```
 Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }
```
When I run it on a different (windows) laptop, connecting over wifi to the server on my first laptop, everything works.

Why doesn't it work on the same laptop?

(Btw, in march last year it was working on this laptop too.)

**Comment by tikue** [comment]
Can you share the code that is failing to connect?

**Comment by Boscop** [comment]
Here: http://dpaste.com/0R51E9Q
But the code works when the client runs on my other laptop, connecting to the server on the first laptop..

Btw, this is the client log:
> 05:52:45 [DEBUG] tokio_core::reactor: adding a new I/O source
05:52:45 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 14211 }
05:52:45 [DEBUG] tokio_core::reactor: loop time - Instant { t: 289449079881 }
05:52:45 [DEBUG] tokio_core::reactor: consuming notification queue
05:52:45 [DEBUG] tokio_core::reactor: consuming notification queue
05:52:45 [DEBUG] tokio_core::reactor: scheduling direction for: 0
05:52:45 [DEBUG] tokio_core::reactor: blocking
05:52:45 [DEBUG] tokio_core::reactor: loop process - 2 events, Duration { secs: 0, nanos: 217905 }
05:52:45 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 5921 }
05:52:45 [DEBUG] tokio_core::reactor: loop time - Instant { t: 289449080560 }
05:52:45 [DEBUG] tokio_core::reactor: loop process - 0 events, Duration { secs: 0, nanos: 76582 }
05:52:46 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 999674326 }
05:52:46 [DEBUG] tokio_core::reactor: loop time - Instant { t: 289451613251 }
05:52:46 [DEBUG] tokio_core::reactor: notifying a task handle
05:52:46 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 160665 }
05:52:46 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 7500 }
05:52:46 [DEBUG] tokio_core::reactor: loop time - Instant { t: 289451613792 }
05:52:46 [DEBUG] tokio_core::reactor: consuming notification queue
05:52:46 [DEBUG] tokio_core::reactor: dropping I/O source: 0
05:52:46 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 218694 }
05:52:46 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 8289 }
05:52:46 [DEBUG] tokio_core::reactor: loop time - Instant { t: 289451614491 }
05:52:46 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 76582 }
05:52:46 [INFO] reconnecting failed: Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }
05:52:50 [DEBUG] tokio_core::reactor: adding a new I/O source
05:52:50 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 13421 }
05:52:50 [DEBUG] tokio_core::reactor: loop time - Instant { t: 289461761756 }
05:52:50 [DEBUG] tokio_core::reactor: consuming notification queue
05:52:50 [DEBUG] tokio_core::reactor: consuming notification queue
05:52:50 [DEBUG] tokio_core::reactor: scheduling direction for: 0
05:52:50 [DEBUG] tokio_core::reactor: blocking
05:52:50 [DEBUG] tokio_core::reactor: loop process - 2 events, Duration { secs: 0, nanos: 238827 }
05:52:50 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 6710 }
05:52:50 [DEBUG] tokio_core::reactor: loop time - Instant { t: 289461762491 }
05:52:50 [DEBUG] tokio_core::reactor: loop process - 0 events, Duration { secs: 0, nanos: 81319 }
05:52:51 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 995669529 }
05:52:51 [DEBUG] tokio_core::reactor: loop time - Instant { t: 289464285051 }
05:52:51 [DEBUG] tokio_core::reactor: notifying a task handle
05:52:51 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 156718 }
05:52:51 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 7895 }
05:52:51 [DEBUG] tokio_core::reactor: loop time - Instant { t: 289464285582 }
05:52:51 [DEBUG] tokio_core::reactor: consuming notification queue
05:52:51 [DEBUG] tokio_core::reactor: dropping I/O source: 0
05:52:51 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 205667 }
05:52:51 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 8289 }
05:52:51 [DEBUG] tokio_core::reactor: loop time - Instant { t: 289464286249 }
05:52:51 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 77372 }
05:52:51 [INFO] reconnecting failed: Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }

**Comment by Boscop** [comment]
It still doesn't work. I still get `Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }` when connecting on a laptop within localhost (client and server on same Windows host), and when trying to connect from another (linux) laptop I get `Connection timed out`, so now that doesn't work anymore!
But it works when I try to connect to the same tarpc server running on the CentOS production server outside of the LAN.
Any idea why it's not working within localhost (on Windows) or within the same LAN anymore?

**Comment by Boscop** [comment]
I found out something weird:
When my tarpc server listens on `localhost:9090` (on Win 8.1), the client running on the same host can connect, everything works.
**BUT:** When I change the tarpc server to listen on `0.0.0.0:9090` (and allow it for both public and private networks in Windows Firewall), then the client **running on the same host** fails to connect with `Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }`. 
How can that be?

Btw, I'm using tarpc 0.11 and tarpc-plugins 0.3. 
I tested it with this test case:
```rust
// common crate
#![feature(plugin, use_extern_macros)]
#![feature(proc_macro_path_invoc)]
#![plugin(tarpc_plugins)]

#[macro_use] extern crate tarpc;

service! {
	rpc register(hardware_id: String, version: u32) -> Result<String, ()>;
}
```
```rust
// client crate 
extern crate common;
extern crate tarpc;

use tarpc::sync::client::{self, ClientExt};

use common::*;

fn main() {
	let client = SyncClient::connect("localhost:9090", client::Options::default()).unwrap();
	println!("{:?}", client.register("windows-1578654".to_string(), 1000).unwrap());
}
```
```rust
// server crate
extern crate common;
extern crate tarpc;
extern crate server_dep;

use tarpc::sync::server;
use tarpc::util::Never;

use common::*;

use std::thread;

#[derive(Clone)]
struct ScaleServer;

impl SyncService for ScaleServer {
	fn register(&self, hardware_id: String, version: u32) -> Result<Result<String, ()>, Never> {
		println!("localhost Hello {}, {}, {}", hardware_id, version, thread::current().name().unwrap());
		Ok(Ok(hardware_id))
	}
}

fn main() {
	// let server = ScaleServer.listen("localhost:9090", server::Options::default()).unwrap();
	let server = ScaleServer.listen("0.0.0.0:9090", server::Options::default()).unwrap();
	println!("{}", server.addr());
	server.run();
}
```
With `0.0.0.0:9090` I get:
```
     Running `D:\projects\tarpc-test\target\debug\client.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { cod
e: 10061, kind: ConnectionRefused, message: "No connection could be made because
 the target machine actively refused it." }', libcore\result.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:463
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:350
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:328
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed<std::io::error::Error>
             at C:\projects\rust\src\libcore\macros.rs:26
  10: core::result::Result<common::SyncClient, std::io::error::Error>::unwrap<co
mmon::SyncClient,std::io::error::Error>
             at C:\projects\rust\src\libcore\result.rs:782
  11: client::main
             at .\src\main.rs:10
  12: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  13: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  14: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:310
  15: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  16: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  17: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:374
  18: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  19: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  20: main
  21: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  22: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  23: BaseThreadInitThunk
  24: RtlUserThreadStart
error: process didn't exit successfully: `D:\projects\tarpc-test\target\debug\client.exe` (exit code: 101)
```

**Comment by tikue** [comment]
Have you tried connecting with a plain tokio TcpStream? The tarpc logic is delegating to the tokio stack for networking. It'd be good to know if this is a more general problem or specific to tarpc.

**Comment by Boscop** [comment]
I had the same issue also on my linux (arch) laptop. When I changed my tarpc server to listen on localhost:9090 instead of 0.0.0.0:9090, it worked!
But it doesn't work to connect from client running on localhost when the server listens at localhost:9090!
So this issue behaves the same on linux and windows.
Any idea why it behaves this way?

I need to allow clients from localhost AND other hosts on the LAN to connect to the server.

**Comment by tikue** [comment]
Sorry for not getting back to you about this sooner. With the latest changes, I've completely torn out any built-in TCP functionality. I'd love to see if you're able to port your code to the latest changes and if your problem is resolved?

**Comment by tikue** [comment]
Note that I haven't released the new version on Crates.io yet, but you can test against master.

**Comment by tikue** [comment]
Closing because I think any lingering problem will exist in a different part of the stack. Please feel free to reopen if you think there's a problem in tarpc!
