### ISSUE TITLE
Consider new constructor functions for Client

### ISSUE THREAD

**Issue by aochagavia** [google/tarpc#18]
`Client::new("127.0.0.1:9000", None)` seems pretty cryptic if you don't remember what the type signature is. I think it would make sense to provide the following functions instead:

```
fn new<A: ToSocketAddrs>(addr: A) -> ...
fn with_timeout<A: ToSocketAddrs>(addr: A, timeout: Duration) -> ...
```

In my opinion, this makes the intent of the programmer more clear, especially in cases when you don't want a timeout.

If you like the idea I could submit a PR. This would probably require bumping the version of the library to 0.3.0 though.

**Comment by tikue** [comment]
We're going to be adding more configuration options as other changes land (to support more transports and making it generic over serialization protocol) so the `Duration` arg is probably going to turn into a config struct. So in the case where you want to just use the defaults it'll probably look like `Client::new("1.2.3.4:0", Config::default())`, which I think will be a readability improvement.

**Comment by tikue** [comment]
Or perhaps `fn new<A: ToSocketAddr>(address: A) -> Client;` and `fn from_config<A: ToSocketAddr>(config: Config<A>) -> Client;`

**Comment by tikue** [comment]
One other option would be `Config::create()`

**Comment by tikue** [comment]
One other option would be `Config::create()`

**Comment by aochagavia** [comment]
Maybe it would be interesting to consider the builder pattern, like used in Piston (see [WindowSettings](http://docs.piston.rs/piston_window/window/struct.WindowSettings.html)).

**Comment by tikue** [comment]
I don't personally think the builder pattern is useful in this case. I think functional struct updates are equivalent.

**Comment by aochagavia** [comment]
That sounds appealing to the Haskeller in me :smile: . Shall I close this issue?

BTW, I left a question on [reddit](https://www.reddit.com/r/rust/comments/46bzyz/announcing_tarpc_a_simple_rpc_library/d051pfk).

**Comment by tikue** [comment]
Let's keep this issue open for reference. I'll probably convert to use a config struct pretty soon (I would also accept a PR if you're interested).

**Comment by aochagavia** [comment]
Unfortunately I won't have time to do this in the short term, so go ahead. I hope to be able to help in the future, though.
