### ISSUE TITLE
Investigate using Tower in lieu of tokio-proto

### ISSUE THREAD

**Issue by tikue** [google/tarpc#184]
Tokio-proto has been dead for a while. Tower, which was [just announced](https://medium.com/@carllerche/announcing-tower-a-library-for-writing-robust-network-services-with-rust-67273f052c40), appears to be its spiritual successor.

**Comment by repi** [comment]
Would this potentially enable creating gRPC services with tarpc?

**Comment by tikue** [comment]
Closing in favor of #199. @repi I only intend for tarpc to support unary requests, and gRPC imposes streaming semantics, so I think there's a bit of an impedance mismatch.
