### ISSUE TITLE
Add example of stateful server to Readme

### ISSUE THREAD

**Issue by JMurph2015** [google/tarpc#188]
Hello!
I was wondering what the semantics are for making a stateful server with tarpc?  I have worked out that we should have fields on the server struct that are wrapped by Mutexes, but I don't quite understand yet how to initialize such a server?
Thanks,
Joseph Murphy

**Comment by JMurph2015** [comment]
It's close, but not quite what I was looking for.  What I'm wondering is the mechanics of starting a server (ie the HelloServer.listen() call) when I need to initialize fields of HelloServer prior to starting up the rpc service.  Can I instantiate a HelloServer struct then call .listen on the struct insta nce?  Here's the workflow I was imagining, but unsure if it would work:
```rust
service! {
    rpc get_state() -> StateReply;
}
pub struct MyServer {
    internal_state: Mutex<MyState>,
}
impl MyServer {
    pub fn new() -> Self {
        let mut internal_state = MyState::new();
        return MyServer{
            Mutex::new(internal_state)
        }
    }
}
impl SyncService for MyServer {
    fn get_state() -> Result<StateReply, Never> {
        // Do stuff
    }
}
pub fn main() {
    let mut server = MyServer::new();
    let mut handle = server.listen("localhost:8080", server::Options::default());
    handle.run();
}
```

**Comment by tikue** [comment]
Yeah, you can do whatever you'd like with your server struct before calling `listen()`. `listen()` takes `self` by value, so once called you won't have access to the struct anymore.

**Comment by tikue** [comment]
(btw, there will be a lot of churn soon, with all the changes to futures and tokio on the near horizon. So this might not stay this way for long.)

**Comment by JMurph2015** [comment]
@tikue Thanks!  I guess I can use some sort of startup RPC to spawn off long running processes that operate on the data.

**Comment by tikue** [comment]
Feel free to reopen if you have further questions.
