### ISSUE TITLE
Code client-server at the same time

### ISSUE THREAD

**Issue by MathieuDutSik** [google/tarpc#210]
I would like to have a server that also works as server (by processing client request) and client (by reaching out to other servers).
Is this at all possible with the tarpc library?
The examples given are strictly client or strictly server. Is there a way to do both client server on a single program?
Thank you for information.

**Comment by tikue** [comment]
Is that like [this](https://github.com/google/tarpc/blob/master/tarpc/examples/server_calling_server.rs) example?

**Comment by MathieuDutSik** [comment]
Thank you and sorry for this clearly inadequate question.

  Mathieu

**Comment by tikue** [comment]
Glad I could be of help! Feel free to open an issue if you'd like to see further documentation of anything else.
