### ISSUE TITLE
example can not compile

### ISSUE THREAD

**Issue by frostRed** [google/tarpc#215]
I have tried master version and v0.14.1 example on the nightly and stable rust. Can't compile in all cases.

OS: Manjaro newest

nightly rust error info
```
no `LocalWaker` in `task`
```

**Comment by tikue** [comment]
Thanks! I'm guessing there have been some changes to the futures API. I'll be able to look at this in the next day or two.

**Comment by tikue** [comment]
So I looked into this, and I think it was actually just because I haven't published a new version recently. I published v0.15.0; give it a spin!

**Comment by frostRed** [comment]
v0.15.0 version compiled perfectly on nightly 2019-03-26. Thank you for your hard work.
