### ISSUE TITLE
use of unstable library feature 'futures_api': futures in libcore are unstable 

### ISSUE THREAD

**Issue by JanYunkai** [google/tarpc#232]
cargo 1.34.0
tarpc = "0.18.0" > Cargo.toml
cargo build

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /Users/xianyi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.16/src/future/future_obj.rs:336:43
    |
336 |         fn from(boxed: Pin<Box<dyn Future<Output = ()> + 'a>>) -> Self {
    |
error: aborting due to 151 previous errors

Some errors occurred: E0432, E0658.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `futures-core-preview`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by tikue** [comment]
Thanks for the report! I can't reproduce this (neither can [travis](https://travis-ci.org/google/tarpc) it seems). I'm guessing the issue is that the latest tarpc version requires Cargo 1.36. Are you able to rustup update?

**Comment by tikue** [comment]
What are your dependencies' versions? Can you try `cargo update`?

**Comment by JanYunkai** [comment]
cargo update
cargo build

[dependencies]
tarpc = "0.18.0"

error[E0599]: no method named `take` found for type `impl futures_core::stream::Stream` in the current scope
  --> src/main.rs:49:10
   |
49 |         .take(1)
   |          ^^^^
   |
   = note: the method `take` exists but the following trait bounds were not satisfied:
           `&mut impl futures_core::stream::Stream : std::iter::Iterator`
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
4  | use futures_util::stream::StreamExt;
   |

**Comment by tikue** [comment]
Can you please paste your code in src/main.rs?

**Comment by JanYunkai** [comment]
copy from this repository`s readme#Example

**Comment by tikue** [comment]
Ah, I see now what you're saying. Sorry, for some reason I didn't realize you had made a project with the code copied from the readme. You're totally right that the readme is unclear about which dependencies are needed. The Cargo.toml needs to be more like this:

```
[dependencies]
tarpc-bincode-transport = "0.7"
futures-preview = { version = "0.3.0-alpha.16", features = ["compat"] }
serde = "1.0"
tarpc = { version = "0.18", features = ["serde1"] }
tokio = "0.1"
tokio-executor = "0.1"
```

I'll update the readme to explain this.

**Comment by JanYunkai** [comment]
it`s work ,thx!
