### ISSUE TITLE
UNIX sockets

### ISSUE THREAD

**Issue by mmstick** [google/tarpc#234]
At System76, I develop system services for Linux, and the desktop applications which connect to them. I'd like to move away from using the dbus RPC mechanism on Linux, and am currently weighing my options between varlink and this. However, I need support for UNIX sockets.

These system services are deployed on every installation of the Pop!_OS Linux desktop. We have various services written in Rust, such as the firmware daemon, power daemon, process scheduler daemon, etc. Rather than exposing these services through opened TCP sockets on end users desktops, we have that communication being performed solely through UNIX sockets managed by dbus.

Looking through the existing examples, I don't see a way to set up RPC based on UNIX sockets. Varlink supports passing an address as a string, such as `unix:@com.System76.ServiceName`, yet it seems that tarpc's `Transport` trait requires IP addresses, which doesn't quite map to what I'm doing here. Am I mistaken, and is it possible to use UNIX sockets with tarpc?

**Comment by tikue** [comment]
Thanks for your interest! I am [working on](https://github.com/google/tarpc/pull/233) removing the IP address requirement. I'd love to hear more about your requirements!

**Comment by curiousleo** [comment]
https://github.com/google/tarpc/pull/233 was closed with "I'll merge something else", but without a link to that something else: https://github.com/google/tarpc/pull/233#issuecomment-510259303.

Am I correct in saying that the state of Unix socket support in tarpc now is that transports are pluggable, so you can write your own Unix socket transport for tarpc, but tarpc does not come with an already-implemented Unix socket transport?

**Comment by tikue** [comment]
@curiousleo that is a correct assessment. We actually no longer directly ship json or bincode transports either. Instead, there's a generic serde transport module that works with codecs that impl a trait provided by the tokio-serde crate.
