### ISSUE TITLE
Does this need nightly?

### ISSUE THREAD

**Issue by mandreyel** [google/tarpc#237]
The readme doesn't explicitly mention it but I suspect nightly is required due to the new async/await syntax usage? If this is the case, it would be good if there was a disclaimer for this near the top of the readme.

**Comment by tikue** [comment]
Good point :) it does indeed need nightly. I suspect we're getting closer to a point where it's no longer needed.

**Comment by mandreyel** [comment]
@tikue Thanks for the response, we'll stick to grpc-rs then, but can't wait to give this one a go on stable rust--exciting times :)

**Comment by vorot93** [comment]
See #242
