### ISSUE TITLE
Use runtime crate in lieu of init fn

### ISSUE THREAD

**Issue by tikue** [google/tarpc#243]
https://github.com/rustasync/runtime

The `runtime` crate provides a runtime-agnostic attach point for async libraries. Importantly, it provides a `spawn` function exactly like the one tarpc uses internally.

**Comment by vorot93** [comment]
The primary developer is on vacation and the library is still very new and its API is not stable yet. It's better to wait for things there to settle a bit.

**Comment by tikue** [comment]
FWIW, tarpc is not stable yet either. I've tried out the runtime crate, and it makes the code quite a bit cleaner.

My main hesitation is whether `runtime` will really become an accepted standard. I believe it's endorsed by the rust async working group?

**Comment by tikue** [comment]
The latest release of `futures-timer` is using `runtime` now: https://crates.io/crates/futures-timer

**Comment by tikue** [comment]
I'm reconsidering this, given the changes required to support #212. To make `Send + 'static` optional requires not baking in any executors. If the executors aren't baked in, then there's no reason to depend on the `runtime` crate.

`tarpc` can provide an optional `runtime` feature that, when enabled, provides some helper functions that spawn things for you. Given that it's an optional feature purely for helper methods, it seems reasonable to be more opinionated about the dependencies used by that feature. Specifically, I'm thinking we can follow [Hyper's lead](https://github.com/hyperium/hyper/blob/master/Cargo.toml#L68-L75) and just depend directly on `tokio` in such an optional feature.

**Comment by tikue** [comment]
Obsoleted by 41c1aaf
