### ISSUE TITLE
How to make blocking RPC?

### ISSUE THREAD

**Issue by zy1994-lab** [google/tarpc#253]
I understand that `tarpc` uses the asynchronous feature of Rust which is pretty cool. However, I'm trying to add `tarpc` to an existing project which I cannot use `async fn` in most places like the `main` function. I spent a long time doing research but fail to find a way of doing blocking RPC. Can you give some example code of doing blocking RPC in `tarpc`. For example, how to rewrite the code in `example/client.rs` to make it a normal function instead of async function. 

```rust
let transport = json_transport::connect(&server_addr).await?;
let mut client = service::WorldClient::new(client::Config::default(), transport).spawn()?;
let hello = client.hello(context::current(), name).await?;
```

Thanks a lot!

**Comment by tikue** [comment]
Hey, good question! I think the best thing to do for this would be to use tokio's [current thread executor](https://github.com/tokio-rs/tokio/blob/master/tokio-current-thread/README.md). Instead of calling `await` you'd do `executor.block_on(client.method(...))`.

**Comment by zy1994-lab** [comment]
Hi Tim, thanks for your reply. I tried the `block_on` method but got the following error.

```rust
let mut runtime = tokio_current_thread::CurrentThread::new();
let transport = runtime.block_on(bincode_transport::connect(&server_addr)).unwrap();
   |                             ^^^^^^^^ the trait `futures::future::Future` is not implemented for `impl std::future::Future`
```

**Comment by tikue** [comment]
hmm, can you show me your Cargo.toml? You may be using an old version of tokio-current-thread.

**Comment by zy1994-lab** [comment]
Thanks, I have updated to `tokio-current-thread = "0.2.0-alpha.1"` which solved the error. But I see another error message at runtime: `thread 'main' panicked at 'the runtime has not been set', src/libcore/option.rs:1166:5`. Can I ask how to set the runtime?
```
fn main() -> io::Result<()> {
    let server_addr = ([127, 0, 0, 1], 18888).into();
    let mut runtime = tokio_current_thread::CurrentThread::new();
    let transport = runtime.block_on(bincode_transport::connect(&server_addr)).unwrap();

    Ok(())
}
```

**Comment by tikue** [comment]
Ah, actually, try using the tokio crate instead, specifically the module `tokio:: runtime::current_thread`. I have an example using that one [here](https://github.com/google/tarpc/blob/f8ba7d9f4ea7eb8f6248fc7b6db42ca3c73f6fe4/tarpc/tests/service_functional.rs#L138).

**Comment by tikue** [comment]
I suspect `tokio_current_thread` assumes there's a full blown runtime already set up.

**Comment by zy1994-lab** [comment]
Thanks! I followed the example and it works!
