### ISSUE TITLE
Github page(google.github.io/tarpc) returns 404

### ISSUE THREAD

**Issue by VPashkov** [google/tarpc#259]
[Github page](https://google.github.io/tarpc) for this repository returns 404.
![google github io_tarpc](https://user-images.githubusercontent.com/1384378/63120261-408b7800-bfa2-11e9-85b2-8783b8985d73.png)

**Comment by tikue** [comment]
Are there any google.github.io repos that don't get a 404 ?

**Comment by tikue** [comment]
I believe this is WAI: https://github.com/google/google.github.io
