### ISSUE TITLE
Why does current_thread perform better?

### ISSUE THREAD

**Issue by zy1994-lab** [google/tarpc#266]
I have the following server code:

```rust
 pub async fn run(self, port: u16, num_of_channels: usize) -> io::Result<()> {
        let server_addr = ([0, 0, 0, 0], port).into();
        let transport = bincode_transport::listen(&server_addr)?;

        transport
            .filter_map(|r| future::ready(r.ok()))
            .map(server::BaseChannel::with_defaults)
            .max_channels_per_key(num_of_channels as u32, |t| {
                t.as_ref().peer_addr().unwrap().ip()
            })
            .max_concurrent_requests_per_channel(num_of_channels)
            .map(|channel| {
                let server = self.clone();
                let (tx, rx) = oneshot::channel();

                current_thread::spawn(async move {
                    channel.respond_with(server.serve()).execute().await;
                    tx.send(()).unwrap();
                });

                rx
            })
            .buffer_unordered(num_of_channels)
            .for_each(|_| async {})
            .await;

        Ok(())
    }

fn main(){
    let mut runtime = current_thread::Runtime::new()
                .unwrap_or_else(|e| panic!("Unable to start the runtime: {:?}", e));
    let run = self.run(port, machines, num_of_channels);
    runtime.block_on(async move {
        if let Err(e) = run.await {
            panic!("Error while running server: {}", e);
        }
    });
}
```

I'm assuming that the server is run using only one thread. So I replaced `current_thread` with `tokio::runtime::Runtime` which should have been more efficient. `&runtime` is  passed to function `run` and `current_thread::spawn` is therefore `runtime.spawn`. However, the performance actually dropped about 20% after this change on a machine with 4 core and 8 threads. Why would this happen?

**Comment by tikue** [comment]
Hey, I'm away this weekend but will try to look into this next week!

**Comment by zy1994-lab** [comment]
Thanks @tikue. Looking forward to your replay.

**Comment by GallagherCommaJack** [comment]
AFAICT from both testing and the documentation, `StreamExt::buffer_unordered` doesn't actually split work up among multiple cores, so you're just getting the overhead of a multithreaded runtime with none of the benefits.

**Comment by tikue** [comment]
@GallagherCommaJack thanks for investigating! I lost track of this. Yes, `buffer_unordered` will only give concurrency, not parallelism. `tokio::spawn` will give parallelism.

**Comment by tikue** [comment]
@zy1994-lab can you share the multithreaded code?

**Comment by zy1994-lab** [comment]
I use `tokio::runtime::Runtime::spawn` inside the map closure, and I'm assuming it creates a multithreaded server. As for the client side, I have 10 machines each running 4 clients to access the server. Will this give true parallelism?

**Comment by GallagherCommaJack** [comment]
using `tokio::spawn` inside the map should work fine.

10 machines each running 4 clients is actually a pretty light load - when I benchmarked over loopback on my 8 thread machine I noticed calls/second going up until around 128-256 connections. Here's the code I used, modified slightly from the default example-service (I've been meaning to clean it up and submit a PR for a few days, but haven't gotten around to it yet).

Do you still get better results with `current_thread` here? When I call `client --num_connections 256' it uses 100% of all available threads, so I'd be pretty surprised if `current_thread` ran better.

[example-service.tar.gz](https://github.com/google/tarpc/files/3817872/example-service.tar.gz)

**Comment by zy1994-lab** [comment]
Thanks Jack @GallagherCommaJack. I benchmarked again and get the same results as yours. The problem should be that I didn't have enough load to actually show the advantages of multithreading.
