### ISSUE TITLE
Why client runs in a blocking way?

### ISSUE THREAD

**Issue by zy1994-lab** [google/tarpc#292]
I am testing the performance of `tarpc` in multithreading environments by modifying the example  code.

```rust
fn hello(self, _: context::Context, name: String) -> Self::HelloFut {
        std::thread::sleep(std::time::Duration::new(1, 0));
        future::ready(format!(
            "Hello, {}! You are connected from {:?}.",
            name, self.0
        ))
    }
```

I added a `sleep` statement in the rpc function on the server side to make the function excuted in about 1 second. One the client side, I spawn 10 requests concurrently.

```rust
let start = Instant::now();

let mut rx = {
    let (tx, rx) = mpsc::unbounded_channel();

    for i in 0u32..10 {
        let tx_clone = tx.clone();
        et mut client_clone = client.clone();
        tokio::spawn(async move {
                let hello = client_clone.hello(context::current(), NAME.into()).await.unwrap();
                tx_clone.send(hello).unwrap();
        });
    }

    rx
};
        
while let Some(hello) = rx.recv().await {
    println!("{}",hello);
}

let duration = start.elapsed();
println!("Time: {:?}", duration);
```

However, there seems no concurrency at all because the client code always takes more than 10 seconds to finish. I have also tried spawn the server threads as mentioned in [issues 266](https://github.com/google/tarpc/issues/266) but nothing worked. I am expecting the client code takes a little bit more than 1 second as the server should be able to handle the requests at the same time. Can anyone suggest the reasons?

**Comment by tikue** [comment]
Which sleep function are you using? The one in std is not async compatible. Try using `tokio::time::delay_for`.

**Comment by zy1994-lab** [comment]
Thanks @tikue. I have tried 2 alternative 'sleep' function:

```rust
        let sleep_time = std::time::Duration::new(1, 0);
        let delay = tokio::time::delay_for(sleep_time);
        while !delay.is_elapsed() {}
```

```rust
        let sleep_time = std::time::Duration::new(1, 0);
        let start = std::time::Instant::now();
        loop {
            if start.elapsed() > sleep_time {
                break;
            }
        }
```

I think the loop here simulates a intensive computation well. But the results are still the same.

**Comment by tikue** [comment]
You don't want to use a loop like that because it will block the whole thread, not just the current future. Instead, try awaiting the delay future: `tokio::time::delay_for(sleep_time).await;`

**Comment by zy1994-lab** [comment]
@tikue Thanks for noticing me. I didn't express my problem clearly, I set the sleep function on purpose to simulate a long running blocking call. I was excepting each request is running in a separate thread given the threadpool is large enough. But I looked on the code again and found out that actually channels are run on a threadpool by all requests in one channel are sequential. Below are my server's code:

```rust
incoming
            .map(|channel| {
                let server = self.clone();

                let (tx, rx) = oneshot::channel();

                handle.spawn(async move {
                    channel.respond_with(server.serve()).execute().await;
                    tx.send(()).unwrap();
                });

                rx
            })
            .buffer_unordered(1024)
            .for_each(|_| async {})
            .await;
``` 

By setting up a new connection for each rpc request instead of clone the shared client, the time did decrease. So is it possible to answer the requests coming in one channels also in a threadpool?

**Comment by tikue** [comment]
I see you're using the execute function, which spawns each response onto the thread pool. So that should be working the way you expect. Can you share your server code?

**Comment by tikue** [comment]
Also, I don't think you need to use the mpsc channel to communicate when the client channel closes, because tokio 0.2 gives you a handle to a spawned task

**Comment by zy1994-lab** [comment]
Here is my server code

```rust
        let server_addr = ("0.0.0.0", port);

        let transport = tarpc::serde_transport::tcp::listen(&server_addr, Bincode::default).await?;
        
        let incoming = transport
            .filter_map(|r| future::ready(r.ok()))
            .map(
                |t| {
                    let mut config = server::Config::default();
                    config.pending_response_buffer = 256;
                    server::BaseChannel::new(config, t)
                }, 
            )
            .max_channels_per_key(32, |t| t.as_ref().peer_addr().unwrap().ip())
            .max_concurrent_requests_per_channel(32);

        incoming
            .map(|channel| {
                let server = self.clone();
                let (tx, rx) = oneshot::channel();

                handle.spawn(async move {
                    channel.respond_with(server.serve()).execute().await;
                    tx.send(()).unwrap();
                });

                rx
            })
            .buffer_unordered(1024)
            .for_each(|_| async {})
            .await;

        Ok(())
```

**Comment by tikue** [comment]
Sorry, what I really want to see is the tarpc service impl (the trait annotated with `#[tarpc::service]`) -- if you're using something like `future::ready` it might be executing your sleeping code before it ever gets to the thread pool.

**Comment by zy1994-lab** [comment]
Thanks Tim. I think you‘ve got to the point.

```rust
impl World for HelloServer {
    // Each defined rpc generates two items in the trait, a fn that serves the RPC, and
    // an associated type representing the future output by the fn.

    type HelloFut = Ready<String>;

    fn hello(self, _: context::Context, name: String) -> Self::HelloFut {

        let sleep_time = std::time::Duration::new(1, 0);

        // intensive computation here
        let start = std::time::Instant::now();
        loop {
            if start.elapsed() > sleep_time {
                break;
            }
        }

        future::ready(format!(
            "Hello, {}! You are connected from {:?}.",
            name, self.0
        ))
    }
}
```

My code executes the sleeping code before it ever gets to the thread pool. How can I revise the code to make the intensive computation actually running on the thread pool?

**Comment by tikue** [comment]
Okay, this should be pretty easy to fix! Change your future type to `Pin<Box<String>>`, then wrap the whole function in `Box::pin(async move { ... })` (remove `ready` as well)

**Comment by zy1994-lab** [comment]
I changed the future type to Pin<Box<String>> and got the following error
```
channel.respond_with(server.serve()).execute().await;
    |                                                 ^^^^^ the trait `core::future::future::Future` is not implemented for `String `
    |
    = note: required because of the requirements on the impl of `core::future::future::Future` for `std::pin::Pin<std::boxed::Box<String>>`
```

**Comment by tikue** [comment]
Sorry, I meant `Pin<Box<dyn Future<Output = String>>>`

**Comment by zy1994-lab** [comment]
Thanks, I have fixed this problem

**Comment by tikue** [comment]
I'm glad to hear! Closing this issue but feel free to reopen if you have more questions.
