### ISSUE TITLE
Examples fail to run against tokio master

### ISSUE THREAD

**Issue by mrkgnao** [google/tarpc#294]
Might be worth a heads-up now; I was trying to integrate the in-process readme example into an existing project that was depending on `tokio` master and got "not currently running on the Tokio runtime" errors.

**Comment by tikue** [comment]
Thanks for the report! To make sure I understand, there is not a released `0.2.X` version of tokio that this is reproducible on? What features currently require the master branch of tokio?

I was under the impression that tokio was going to maintain compatibility with `0.2` for a long time. Perhaps a bug should be filed with them as well?

**Comment by mrkgnao** [comment]
I think I was using something in `tokio-util` only available in master at that point, so I decided to also use `tokio` master just in case I had any compatibility issues. (I've since moved away from `tokio` and am running on `async-std` instead at present.)

**Comment by vorot93** [comment]
Most likely because of two `tokio` versions in the dependency graph - hence two separate runtime contexts to initialize. Not a bug.
