### ISSUE TITLE
Internal panic in increment_channels_for_key

### ISSUE THREAD

**Issue by cswinter** [google/tarpc#304]
tarpc sometimes panics at [filter.rs:230](https://github.com/google/tarpc/blob/d905bc159148b2fafbec97d6323b7fed7772ffc3/tarpc/src/rpc/server/filter.rs#L230) with ```'called `Option::unwrap()` on a `None` value'```. I don't have a minimal example/reliable way to reproduce, the program where this happens configures high limits for max channels/max channels per key and quickly creates/drops many clients to a server running on localhost.

**Comment by cswinter** [comment]
Adding a connection pool that reuses clients to all destinations (rather than creating a new client on each request) seems to make the panic disappear in my case. It would still be quite desirable to find a fix since the panic could be triggered by reasonable usage. E.g. a connection pool with a bounded number of active connections may be forced to drop/recreate clients at a high rate.

**Comment by tikue** [comment]
Thank you for the report! I'll look into it.

**Comment by tikue** [comment]
I think this was fixed in https://github.com/google/tarpc/commit/a11d4fff58d791a603130642468741165e640c39. I'll publish a new version with the fix.

**Comment by tikue** [comment]
I've release v0.21.0 which contains this fix.
