### ISSUE TITLE
Clarifications on `Context`

### ISSUE THREAD

**Issue by cswinter** [google/tarpc#308]
1. The [docs for `context`](https://docs.rs/tarpc/0.21.0/tarpc/rpc/context/index.html) indicate that it is sent to the server and used to enforce response deadlines. The `Context` struct uses an absolute time, what is the expected behavior when clocks on the server and client are out of sync?

2. To create a `Context` with a custom deadline I have this snippet, maybe an equivalent method could be included in tarpc alongside `context::current()`? (happy to make a PR)

```
use std::time::{Duration, SystemTime};

use tarpc::context::{self, Context};

pub fn with_deadline(duration: Duration) -> Context {
    let mut ctx = context::current();
    ctx.deadline = SystemTime::now() + duration;
    ctx
}
```

3. For (short) client side timeouts, I assume wrapping requests in something like the tokio [`Timeout`](https://docs.rs/tokio/0.2.21/tokio/time/fn.timeout.html) future is the correct approach, rather than setting a deadline on the `Context`?

**Comment by tikue** [comment]
Hi!

1. This is a great question! If the server time is ahead of the client time, in the extreme case the server will set a timeout of 0 and instantly cancel processing. If the server time is behind the client, then it will allow processing to last longer than it should. This isn't ideal behavior, but I think using relative timeouts would just trade those problems for a different set of problems -- e.g. time spent in the outbound queue or on the wire wouldn't be accounted for.
2. I would happily accept a `with_deadline` method on Context!
3. Can you give an example? If you drop a request, it will send a cancellation message to the server. Also, tarpc clients already wrap their requests in the tokio Timeout future ([code](https://github.com/google/tarpc/blob/master/tarpc/src/rpc/client/channel.rs#L140)).

**Comment by cswinter** [comment]
Thanks the quick and detailed response! Re 3., the specific case I was thinking about is something where I want fairly short timeouts (tens to hundreds of milliseconds) which could easily run into clock drift, in which case setting this deadline on the `Context` seems dangerous.

Related question, is there a way to set up a connection timeout separately from a response timeout?
It looks like if a client cannot contact the server it will still retry until the deadline from the `Context` and then eventually error, and log `[2020-07-10T01:48:46.835Z ERROR tarpc::rpc::client] Connection broken: Broken pipe (os error 32)`.
I would like to have an option to have requests fail immediately if a connection has been reset/cannot be established, and probably not perform error level logging and just return an error result since this might be expected during normal operation.

**Comment by cswinter** [comment]
Looks like tarpc actually already does what I describe on connection failures and the behavior I was seeing was more related to shutdown.

**Comment by tikue** [comment]
I would totally believe that sometimes the TCP connection takes a long time to realize it's disconnected. I've looked into it before, but I didn't find any obvious fixes. It seemed to just be a quirk of the protocol. If you see this behavior again and want to add additional data points, feel free to reopen :)
