### ISSUE TITLE
Subscriber requires a public address

### ISSUE THREAD

**Issue by garious** [google/tarpc#313]
It's odd how the client starts a subscriber on a public-facing address and that the publisher needs to know what transport it chose.  Have you given thought to a version of pubsub that utilizes the client connection? I'd like to connect to the server with clients from behind a NAT.

**Comment by tikue** [comment]
Yep! There's no reason you couldn't do this :) the pubsub example is just that -- an example. Once the client establishes the connection, the server can send requests over it as the client and the client can receive as the service.

I'd accept a pr changing the example to do this :)

**Comment by tikue** [comment]
I think this example predates the generic transport layer, so at the time the only way to do it would have been for the client to  listen for publisher connections.

**Comment by garious** [comment]
Wow, thanks @tikue! 🥇 4 hours from "I'd accept a pr changing the example" to "tikue closed this in ebd245a"  😅

**Comment by tikue** [comment]
Sorry, I hope you weren't already working on it 😇 this was actually something previously on my radar, so you bringing it up was all the motivation I needed. Please do let me know if you have any questions about the example!

**Comment by garious** [comment]
Nah, not all, but always happy to compete! The example is tougher to digest than others. It looks like the publisher still has some knowledge of the subscriber code (other than its `receive()` method).  I was thinking there ought to be a `subscribe()` method on Publisher, such that you can `publisher.subscribe(subscriber)`, where `subscriber` is either a `SubscriberClient` or perhaps a handle.  Maybe this is a simple reorg of the same code - I haven't had time to really dig in yet.

**Comment by tikue** [comment]
(quick shout out to the tarpc [discord](https://discord.gg/VPRbWz), if you prefer synchronous conversations)

So the way I did this is there is one PubSub server and two types of clients that connect to the server.

1. The PubSub server sets up TCP listeners on 2 ports, the "subscriber" port and the "publisher" port. Because both publishers and subscribers initiate their connections to the PubSub server, the server requires no prior knowledge of either publishers or subscribers.
2. Subscribers connect to the server on the server's "subscriber" port. Once the connection is established, the server acts as the client, sending messages to the subscribers via a Subscriber service. 
3. Publishers connect to the server on the "publisher"port, and once connected, they send messages to the server to be broadcast via a Publisher service.

```
      Subscriber                        Publisher                       PubSub Server
T1        |                                 |                                 |             
T2        |-----Connect------------------------------------------------------>|
T3        |                                 |                                 |
T4        |                                 |-----Connect-------------------->|
T5        |                                 |                                 |
T6        |                                 |-----Publish-------------------->|
T7        |                                 |                                 |
T8        |<------------------------------------------------------Receive-----|
T9        |-----(Receive OK)------------------------------------------------->|
T10       |                                 |                                 |
T11       |                                 |<--------------(Publish OK)------|
```

**Comment by tikue** [comment]
It may be that the name of the RPC `Subscriber::receive` is confusing, because the server calls `subscriber.receive()` but that's actually sending a message, not receiving. Perhaps it'd be clearer if it was called `subscriber.process_message()` ?

**Comment by garious** [comment]
A name like `on_notification()` might be better, but that's not the issue for me. I get hung up on registering the subscriber. Consider, for example, a stateless callback:

```rust
let callback = MyClient::new().spawn();
publisher.call_it(callback);
```

Can you pass the publisher a client or handle, such that it can immediately make an RPC call back to that input client?
