### ISSUE TITLE
Upgrade to Tokio v0.3

### ISSUE THREAD

**Issue by Urhengulas** [google/tarpc#318]
Tokio v0.3 [just released](https://tokio.rs/blog/2020-10-tokio-0-3). Would be nice to upgrade 🙂

**Comment by tikue** [comment]
Thanks for the heads up! I'll try to do it in the next few weeks. I'm kind of maintaining two branches right now, which might slow down this upgrade, depending on how much is involved.

**Comment by Urhengulas** [comment]
@tikue I am happy to support a bit here. Should I have a look onto the master branch?

**Comment by tikue** [comment]
You're more than welcome to have a go at it :)

**Comment by Urhengulas** [comment]
I think I got most of the required changes on master. 
You can have a look here: https://github.com/Urhengulas/tarpc/pull/1

**Comment by tikue** [comment]
@Urhengulas looks great! I eagerly await your PR ☺️

**Comment by Urhengulas** [comment]
> @Urhengulas looks great! I eagerly await your PR ☺️

Still need to adapt some tests, but else we should be good 😉

**Comment by Urhengulas** [comment]
> Edit: If you're interested in porting the tokio upgrade to my experimental branch, it's https://github.com/tikue/tarpc/tree/gats

@tikue I will just try to cherry-pick it over. Probably there isn't much more to do there.

**Comment by Urhengulas** [comment]
@tikue Would it be possible that you publish a `0.22.1` version with `tokio 0.3`?

**Comment by tikue** [comment]
Done!

**Comment by Urhengulas** [comment]
> Done! Since it's a breaking change, it needed to be 0.23.

Thanks a lot :D
