### ISSUE TITLE
Type for arbitrary server

### ISSUE THREAD

**Issue by Urhengulas** [google/tarpc#323]
Hello @tikue,

I'd like to write a function returning a server with various configuration, but can't figure out a good return type for this...
I assume it needs to be a `Future<Output=...>`, but not sure about the details.

I added a `fn get_server(...)` to the example from the README to make it clear:
```rust
use futures::{
    future::{self, Ready},
    prelude::*,
};
use std::io;
use tarpc::{
    client, context,
    rpc::transport::channel::UnboundedChannel,
    server::{self, Handler},
};

// This is the service definition. It looks a lot like a trait definition.
// It defines one RPC, hello, which takes one arg, name, and returns a String.
#[tarpc::service]
trait World {
    /// Returns a greeting for name.
    async fn hello(name: String) -> String;
}

// This is the type that implements the generated World trait. It is the business logic
// and is used to start the server.
#[derive(Clone)]
struct HelloServer;

impl World for HelloServer {
    // Each defined rpc generates two items in the trait, a fn that serves the RPC, and
    // an associated type representing the future output by the fn.

    type HelloFut = Ready<String>;

    fn hello(self, _: context::Context, name: String) -> Self::HelloFut {
        future::ready(format!("Hello, {}!", name))
    }
}

#[tokio::main]
async fn main() -> io::Result<()> {
    let (client_transport, server_transport) = tarpc::transport::channel::unbounded();

    tokio::spawn(get_server(server_transport));

    // WorldClient is generated by the macro. It has a constructor `new` that takes a config and
    // any Transport as input
    let mut client = WorldClient::new(client::Config::default(), client_transport).spawn()?;

    // The client has an RPC method for each RPC defined in the annotated trait. It takes the same
    // args as defined, with the addition of a Context, which is always the first arg. The Context
    // specifies a deadline and trace information which can be helpful in debugging requests.
    let hello = client.hello(context::current(), "Stim".to_string()).await?;

    println!("{}", hello);

    Ok(())
}

fn get_server(server_transport: UnboundedChannel<_, _>) -> impl Future<Output = _> {
    server::new(server::Config::default())
        // incoming() takes a stream of transports such as would be returned by
        // TcpListener::incoming (but a stream instead of an iterator).
        .incoming(stream::once(future::ready(server_transport)))
        .respond_with(HelloServer.serve())
}
```

So – what would be a good functions signature for this kind of function? 
Thx in advance!!

**Comment by Urhengulas** [comment]
https://docs.rs/tarpc/0.23.0/tarpc/rpc/server/trait.Serve.html also seems like it might be a fit...

**Comment by tikue** [comment]
Hey, good question! `incoming.respond_with()` will end once the incoming connection is closed. In the way you've written it, where it's wrapping a single transport, that future will end immediately, but you would need to keep driving your executor for each open channel.

In general, `incoming.respond_with()` is only intended for uses where you'll have a socket listener open for a long time and have many clients connecting. If you only are connecting to a single client, it may be easier to use `BaseChannel` directly.

**Comment by Urhengulas** [comment]
Thanks for the answer 😸  I will try to get it working with `BaseChannel`.

The code above is more of an example. In my actual application it should look like:
```rust
fn get_server(...) -> ... {
    tarpc::serde_transport::tcp::listen(&CONFIGURATION.get().unwrap().rpc_socket(), Json::default)
        .await?
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        .max_channels_per_key(1, |t| t.as_ref().peer_addr().unwrap().ip())
        .map(|channel| {
            let server = BookServer(channel.as_ref().as_ref().peer_addr().unwrap());
            channel.respond_with(server.serve()).execute()
        })
        .buffer_unordered(10)
        .for_each(|_| async {})
}
```

**Comment by tikue** [comment]
That code looks great; in particular, the returned future will not resolve until all clients have closed their connections. In that case, I think it's perfectly reasonable to return `impl Future<Output = ()>`.

**Comment by Urhengulas** [comment]
Yes. I also figured that this would be the most flexible option 🙂 

On the other hand I'd like to access some methods like [`Incoming::local_addr()`](https://docs.rs/tarpc/0.23.0/tarpc/serde_transport/tcp/struct.Incoming.html#method.local_addr), but I guess I can also just return the `SockerAddr` as additional return parameter.

**Comment by Urhengulas** [comment]
_On a sidenode: For questions like this the github discussions ([link](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-team-discussions)) might be a good solution :)_

**Comment by tikue** [comment]
> _On a sidenode: For questions like this the github discussions ([link](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-team-discussions)) might be a good solution :)_

Thanks for pointing that out! I'll need to look into it (I might need to route a request to the Google Org admins).

**Comment by Urhengulas** [comment]
@tikue 
I am now going with:
```rust
pub async fn rpc_server(addr: &SocketAddr) -> io::Result<(impl Future<Output = ()>, SocketAddr)> {
    ...
}
```
