### ISSUE TITLE
Remove the #[derive(Debug)] on library structs

### ISSUE THREAD

**Issue by cpcloud** [google/tarpc#326]
Placing a `#[derive(Debug)]` on user facing library structs that have generics puts an unnecessary burden on users of the library because now the user's type must implement `Debug` even if it has no business doing so.

It's completely fine to `#[derive(Debug)]` on structs that are not generic and/or hold instances of types constructed by users.

Is there any particular reason why the structs in `rpc/server.rs` for example derive Debug?

**Comment by cpcloud** [comment]
Another reason not to do this is that if a user's type contains types they don't have control over, say from another crate, then they must wrap all of those types in a newtype struct and implement Debug for that. That itself will not be that useful because the fields on such a type are likely private.

**Comment by tikue** [comment]
Seems pretty straightforward to fix! I'll probably be able to get to this in the next week or so. Contributions are also welcome.

**Comment by chansuke** [comment]
I'd like to work on this issue.

**Comment by tikue** [comment]
Thanks @chansuke! I've assigned this to you.
