### ISSUE TITLE
Server does not reply to client in my example

### ISSUE THREAD

**Issue by Ploppz** [google/tarpc#334]
This is more of a help question.
I tried to reproduce the example-service but with a different transport (from `interprocess` crate).
The problem is that when I start the client (while server is running), I get the error `TimedOut, error: "Client dropped expired request."`.

I put some `println!` in the server and it prints
```
Incoming connection
Creating server
```
But there is also a `println!` in the `hello` method itself, that shows that `hello` is not actually called.

Repo: https://github.com/Ploppz/tarpc_interprocess/tree/99fbfcca02342ad7752872fdfce20876f5511239
server.rs and client.rs are similar to your example-service but using interprocess (unix socket) rather than TCP.
Any idea what I did wrong, or what I can do further to see what's wrong?

**Comment by Ploppz** [comment]
I added logging with Trace level, and full backtrace.

Here is what the client logs:
```
Nov 21 12:20:56.522 TRCE [3a5c7dfff57bcffa50] Queuing request with timeout 9.9998989s.
Nov 21 12:20:56.523 TRCE flushing framed transport
Nov 21 12:20:56.523 TRCE flushing framed transport
Nov 21 12:20:56.523 TRCE writing; remaining=75
Nov 21 12:21:06.523 DEBG [3a5c7dfff57bcffa50] Removed request.
Nov 21 12:21:06.523 TRCE [3a5c7dfff57bcffa50] Cancel message sent.
Nov 21 12:21:06.523 TRCE flushing framed transport
Nov 21 12:21:06.523 TRCE writing; remaining=124
```
The rest is a bit more verbose.
Here is the full backtrace when client panics https://gist.github.com/Ploppz/79c507d929209027831872eaae25435b which does show some entries from `tarpc.

Server logs a lot of
```
Nov 21 12:21:06.680 TRCE flushing framed transport
Nov 21 12:21:06.680 TRCE framed transport flushed
```
And then in the end
```
Nov 21 12:21:06.681 INFO ClientHandler finished.
```

**Comment by tikue** [comment]
Based on what you've described, I suspect the server's transport is failing to read the request. Perhaps deserialization is failing, but it could be done other error in the transport layer.

This does shine a light on the lack of helpful logging in the 
connection error path.

**Comment by Ploppz** [comment]
Thanks for your reply.

Is it normal that the client sends a cancel message?
I will do as you suggest and add logging to transport.
For now, can you point out one good place to add logging/printing in `tarpc` to catch the possibility of deserialization error? To cover all bases.

**Comment by Ploppz** [comment]
I could not catch any error happening in the transport (so far).
I went to `tarpc` commit `7dd7494`, difff:

```
diff --git a/tarpc/src/serde_transport.rs b/tarpc/src/serde_transport.rs
index 3aac5d5..0eb2406 100644
--- a/tarpc/src/serde_transport.rs
+++ b/tarpc/src/serde_transport.rs
@@ -42,14 +42,18 @@ where
     type Item = io::Result<Item>;

     fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<io::Result<Item>>> {
-        match self.project().inner.poll_next(cx) {
+        let res = match self.project().inner.poll_next(cx) {
             Poll::Pending => Poll::Pending,
             Poll::Ready(None) => Poll::Ready(None),
             Poll::Ready(Some(Ok::<_, CodecError>(next))) => Poll::Ready(Some(Ok(next))),
             Poll::Ready(Some(Err::<_, CodecError>(e))) => {
                 Poll::Ready(Some(Err(io::Error::new(io::ErrorKind::Other, e))))
             }
+        };
+        if let Poll::Ready (Some(Err(ref e))) = res {
+            log::error!("Error in Transport::poll_next: {}", e);
         }
+        res
     }
 }
```

But no error comes from here. Any idea what I should try next? Where can it fail silently?

**Comment by tikue** [comment]
Yes, clients will send cancel messages if they haven't received a response by the request deadline.

Looking more closely at your logs, the ClientHandler doesn't finish until after the request is cancelled, which indicates it was in fact *not* a transport error. If it were, the ClientHandler would finish immediately.

It's possible a message is never being read from the transport on the server side. Could something be causing it to deadlock? I don't know much about the local socket transport you're using. Could you try with a tcp transport to see if the problem still occurs?

**Comment by Ploppz** [comment]
With TCP transport, it works.

Here's what changed: https://github.com/Ploppz/tarpc_interprocess/commit/32690f37fadc43283d8017e45bc12f2e3dbd8021

**Comment by Ploppz** [comment]
Some examples were created to test capabilities of `interprocess`, and that it acts similar to a TCP interface.
https://github.com/kotauskas/interprocess/tree/master/examples
The teletype examples works as expected on my PC.

Any idea for further tests/examples we can write for `interprocess` to verify that it behaves as tarpc expects?
Or maybe we would have more success with logging in `tarpc` when transport errors, as you mentioned. But I'm unsure where to put that, can you point me to somewhere in the code to start @tikue ?

**Comment by tikue** [comment]
I'm not able to build on my laptop due to Mac-specific build errors in interprocess; see this [gist](https://gist.github.com/tikue/aff65a0da93f42fbc657ceaedd858224).

I filed https://github.com/kotauskas/interprocess/issues/3.

**Comment by tikue** [comment]
@Ploppz was this issue resolved?

**Comment by Ploppz** [comment]
I don't know, I stopped working on it. I'll reopen if I start working on it again and get the same issue
