### ISSUE TITLE
Will tarpc wait for completion of a function that returns nothing?

### ISSUE THREAD

**Issue by Ploppz** [google/tarpc#335]
I have been considering the feasibility of using `tarpc` in a networked game where latency is important. A few of the requests the client would send to the server requires a reply, and that's where we need something like `tarpc` to correlate response to request in a transport channel.

Since most cases (so far) in networking in our game is fire-and-forget messages, I was wondering if `tarpc` could double as a general protocol for that case, and for request-and-reply when needed. Then it's important to know whether making a remote procedure call on a function that returns nothing would await its completion.
If so, is there some way to customize this behaviour and if not, maybe it would be an idea?
(Otherwise I could obviously just use one transport channel (we use QUIC) for request-and-reply cases and one without tarpc for fire-and-forget messages)

**Comment by tikue** [comment]
By "returns nothing", do you mean that the client doesn't care whether the request even made it to the server? Today, every client request waits for a response, and the server will send a response for every request received. You can of course have an RPC where the response is `()` (`rpc request_with_empty_response(request: Request);`), but there's still some overhead associated with sending and receiving the response.

**Comment by Ploppz** [comment]
Thanks for the information. When I think about it, in any case of reliable network channel we obviously in some way or another have to wait for reply from a server. So I think now that if we really wanted to use tarpc for reliable "shoot and forget" messages we would probably want a thread to facilitate this, which drives the procedure calls to completion.

**Comment by tikue** [comment]
Cool! That sounds good to me. I also have a toy game server that does fire-and-forget by spawning background work and returning (). :)
