### ISSUE TITLE
Unexpected errors when using cbor or bincode for serialization

### ISSUE THREAD

**Issue by cswinter** [google/tarpc#336]
I'm getting connection resets when using bincode or cbor for serialization.
The same code works fine with jason.
Not sure where the error originates, the server seems to work fine but the client returns with `Kind(ConnectionReset)`.
I'm seeing this in the logs but nothing else (apart from `TRACE mio::pol` logs):

```
[2020-12-15T00:36:00.504Z ERROR tarpc::rpc::client] Connection broken: failed to read from transport
```

It would be useful to show a more informative error, it took very long to even realize this was even related to serialization.

In some case I am also seeing this error:

```
[2020-12-15T00:33:01.325Z INFO  tarpc::rpc::server] ClientHandler errored out: Bincode does not support the serde::Deserializer::deserialize_any method
```

Any ideas why this might happen?

**Comment by tikue** [comment]
Hi! Sorry about the bad error message. That's coming from [here](https://github.com/google/tarpc/blob/026083d653050ed56a2d8d2aa161cf7cfb895020/tarpc/src/rpc/client/channel.rs#L450). This is a client-side error. The client side doesn't know why the server killed the connection. The server is unable to parse the message, so it has no reason to believe sending a message would succeed.

> Bincode does not support the serde::Deserializer::deserialize_any method

This can happen if a type being deserialized calls `deserialize_any` on the Bincode deserializer. [Here's a similar issue](https://github.com/servo/bincode/issues/85). Can you share the types you're trying to deserialize? I suspect that you have a request parameter type that implements Deserialize by calling `deserialize_any`.

**Comment by cswinter** [comment]
There are two ways the error happens, either client successfully sends a request works and the server processes the request (and then fails to write response?) or the send already fails at the client. I haven't confirmed it yet, but it seems to be caused by types that contain a [ron::Value](https://docs.rs/ron/0.6.2/ron/value/enum.Value.html).

I'm not really familiar with this particular feature of serde, would this be considered a bug in RON or does tarpc require a more extensive set of functionality than guaranteed by the standard serde traits?

**Comment by tikue** [comment]
Ah, yes, it looks like the `impl<'de> Deserialize<'de> for Value` [uses deserialize_any](https://docs.rs/ron/0.6.2/src/ron/de/value.rs.html#32).

This is not directly related to tarpc; it would be considered a feature request against `ron` to support `Bincode`. [Similar PRs](https://github.com/chronotope/chrono/pull/89) have been made against other libraries to support Bincode.

**Comment by tikue** [comment]
Closing but feel free to reopen if you have any further questions!
