### ISSUE TITLE
AtomicU64 availability

### ISSUE THREAD

**Issue by M1cha** [google/tarpc#339]
on MIPS, `AtomicU64` is not available and thus, this crate does not compile.
I could make a PR to fix that but first I need to know which solution you prefer:
1. switch to `AtomicUsize`
2. use `#[cfg(target_arch)]` to use `AtomicU32` for MIPS
3. use a 64bit Mutex
4. use a Generic

Also, in my quick n' dirty solution where I did `1.` I then casted the resulting `usize` to `u64` so I don't have to change the whole API. How do we go about that?

**Comment by tikue** [comment]
Hey, thanks so much for bringing this up! I think I am fine with `AtomicUsize` for calculating the next request ID. I support not changing the public API, since u64 is stable across platforms.
