### ISSUE TITLE
in-flight requests don't get dropped when the connection closes

### ISSUE THREAD

**Issue by M1cha** [google/tarpc#341]
If the client closes the connection, the server correctly detects that the read-half was closed but continues waiting for the response of all requests even though the write-half might already be gone as well.

This is the use-case were this is a problem(is that out of scope for this crate?):
- you start a request like `run_service` without a timeout(currently, a very long timeout since it's not optional yet)
- the request handler starts that service and waits until it's completion which is basically forever unless explicitly stopped from the server side
- when the client gets stopped, the connection gets closed, the server should see that and drop the future of the request handler (which would stop the service)

Right now, the request handler waits for tarpc to drop the future after the connection closed while tarpc waits for the request handler to finish before doing so.

This is the responsible piece of code: https://github.com/google/tarpc/blob/v0.24.1/tarpc/src/rpc/server.rs#L460
I'm not yet sure ho to handle that correctly with the current logic, That's why I'm creating this issue instead of a PR which would change that behavior.

**Comment by tikue** [comment]
This is pretty interesting! I'm not sure I would recommend starting a running service bound to the lifetime of a request. I don't see a problem using a request to kick off the startup of a service, but what about instead binding the service to the lifetime of the client connection?

**Comment by tikue** [comment]
I do think that when a client connection is shut down, the tarp server could go clean up any lingering requests.

**Comment by tikue** [comment]
Ok, I just took a closer look, and this is actually a very simple fix! I should be able to have a fix in today.

**Comment by tikue** [comment]
I just pushed a fix for this to the master branch; can you give it a whirl? If it works for you, I'll publish a new release fixing this (major increment, since it's technically a breaking change).

**Comment by tikue** [comment]
Closing, but feel free to reopen if you have any problems.
