### ISSUE TITLE
tarpc/tarpc/examples/compression.rs sends uncompressed messages

### ISSUE THREAD

**Issue by Type1J** [google/tarpc#348]
`tarpc/tarpc/examples/compression.rs` seems to compress, then uncompress, then send, then compress again on the receiving side, then uncompress again.

My expectation is that the send operation would transfer the compressed payload, which is then uncompressed the receiving side.

**Comment by tikue** [comment]
Hey there! Is your understanding based on the code, or have you run some tests? I won't be able to test it myself for a few days probably, but based on my understanding of the code, I would be surprised if it behaved the way you suggest: the line `    transport.with(compress).and_then(decompress)` means outbound messages are compressed while inbound messages are decompressed (`with` applies a preprocess to messages being sent over the transport while `and_then` applies a postprocess to messages received by the transport).

**Comment by Type1J** [comment]
Dropping some `println!("compress");` and `println!("decompress");` lines at the beginning of the `compress()` and `decompress()` functions do show that 1 message makes them both run twice:
```
tarpc/tarpc/examples on  master [!?] via 🦀 v1.53.0
❯ cargo run --features "serde-transport tcp" --example compression
   Compiling tarpc v0.26.2 (C:\Projects\tests\tarpc\tarpc)
    Finished dev [unoptimized + debuginfo] target(s) in 7.88s
     Running `C:\Projects\tests\tarpc\target\debug\examples\compression.exe`
compress
decompress
compress
decompress
Hey, friend!
```

**Comment by Type1J** [comment]
Oh! I just figured out why. I changed the message types to be serialized to pretty printed JSON, and then printed the message in the compress function before the compression. I was wrong; The compress and decompress are run twice, but not on the same things. The first time is for the request, and the second time is for the response. I guess the fact that the server and the client are in the same process somehow confused me.
```
compress
{
  "Request": {
    "context": {
      "deadline": {
        "secs_since_epoch": 1628806381,
        "nanos_since_epoch": 818718000
      },
      "trace_context": {
        "trace_id": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "span_id": 15238786407264056919,
        "sampling_decision": "Unsampled"
      }
    },
    "id": 1,
    "message": {
      "Hello": {
        "name": "friend"
      }
    }
  }
}
decompress
compress
{
  "request_id": 1,
  "message": {
    "Ok": {
      "Hello": "Hey, friend!"
    }
  }
}
decompress
```
