### ISSUE TITLE
disable logging until a set level for tarpc

### ISSUE THREAD

**Issue by OfekShochat** [google/tarpc#354]
hi, Im making something with tarpc and logging with env_logger and Id like only my logs to be shown. can that be done?
thanks aot

**Comment by tikue** [comment]
Hi! Can you use a filter like `RUST_LOG=tarpc=error`?

**Comment by OfekShochat** [comment]
that sounds exactly what I need. thank you so much! Im sure it works but I cant test it for the near future (a matter of an hour or so). will update you for the sake of security

**Comment by OfekShochat** [comment]
hmm, it seems like it doesnt show my infos anymore if I do that.. @tikue

**Comment by tikue** [comment]
You can put multiple comma-separatwd filters, like RUST_LOG=debug,tarpc=error # default to debug, filter out <error msgs for tarpc

**Comment by OfekShochat** [comment]
ok that was my gap of understanding. I thought of doing this just ':' separated like linux paths :sweat_smile:

**Comment by OfekShochat** [comment]
yep this works perfectly. thank you so much!
