### ISSUE TITLE
Colors are weird

### ISSUE THREAD

**Issue by TerraDOOM** [google/tarpc#364]
Colors are mismatched somewhere in the engine, I suspect it to be linear/sRGB.

**Comment by tikue** [comment]
Hi, thanks for filing! I'm not sure what colors you're referring to? tarpc doesn't do any coloring; it's just an RPC framework.

**Comment by tikue** [comment]
Closing this, but feel free to reopen if I've misunderstood something!

**Comment by TerraDOOM** [comment]
I'm so sorry, I don't know how this issue ended up on this project, I believe I intended to file it on a personal project completely unrelated, and must've accidentally been on this repo. My sincerest apologies for this mistake, and also the lack of communication on my part.

**Comment by tikue** [comment]
No worries, thanks for letting me know!
