### ISSUE TITLE
How to separate project for Cargo.lock file

### ISSUE THREAD

**Issue by createyourpersonalaccount** [google/tarpc#365]
Hello,

The [Cargo.lock file](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) is treated differently for library versus binary targets by Cargo. 

With the project structure as in the [example-service](https://github.com/google/tarpc/tree/master/example-service) you have, the library is not logically separated from the server. In my use-case, the library is public and I should not commit `Cargo.lock` with it; while the server is a daemon that should have `Cargo.lock` committed with it for reproducibility. This is explained in detail here:  [Why do binaries have Cargo.lock in version control, but not libraries?](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).

If you could elaborate on this point I would appreciate it.

**Comment by tikue** [comment]
Hi! I think the Cargo.lock is only used by binaries. Any project only depending on the [lib] won't use the Cargo.lock, but it will be used by the [[bin]]s.

**Comment by createyourpersonalaccount** [comment]
@tikue Hello there. You are right! thanks for the insight.
