### ISSUE TITLE
Update outdated dependencies or re-export 

### ISSUE THREAD

**Issue by kkharji** [google/tarpc#370]
It would be great to have the dependency updated like tokio and others. Also, it might be easier on maintainer and users to just re-export.

Right now and maintaining a specific version for the following to ensure compatibility with tarpc

 
```rust
pub use tokio_serde::formats::Json;
pub use tokio_util::codec::length_delimited::LengthDelimitedCodec;
```

I'm happy to open a PR

Thanks

**Comment by tikue** [comment]
Thanks for filing this! I agree re-exporting would be easier for users. A PR would be most appreciated!

**Comment by tikue** [comment]
Actually, for the first one, I believe tarpc does already re-export tokio_serde, so you should be able to do this in your crates:

```rust
use tarpc::tokio_serde::formats::Json;
```
