### ISSUE TITLE
log spammed with `OpenTelemetry subscriber not installed; making unsampled child context` when used w/o Otel

### ISSUE THREAD

**Issue by Licenser** [google/tarpc#373]
When using tarpc without otel it spams the logs with `OpenTelemetry subscriber not installed; making unsampled child context` on every request. This makes it quite unpleasant to use in this kind of scenario. It would get nice if the warning were limited to a single startup message instead of [on every call](https://github.com/google/tarpc/blob/master/tarpc/src/client.rs#L131) or gated by a feature flag that selectively enables (or disables) OTel integration.

**Comment by tikue** [comment]
Thanks for filing! I think the log level is too verbose right now. Would it be less intrusive if the log level were trace instead of warn?

**Comment by Licenser** [comment]
Definitely, that would be totally fine for a solution! Thanks for the quick reply :) <3

**Comment by tikue** [comment]
Fixed by https://github.com/google/tarpc/commit/453ba1c074eebd31f6653e25744af9a54c79b9f7
