### ISSUE TITLE
Example code only seems to work if I change the server to use ipv4

### ISSUE THREAD

**Issue by CaliViking** [google/tarpc#381]
If I try to provide an ipv6 address in the client (say ::1:8080) the client refuses to accept the format.

I changed the code in the server to use ipv4:
`let server_addr = (IpAddr::V4(Ipv4Addr::LOCALHOST), flags.port);`

I can now connect with an ipv4 address from the client.

Am I doing this wrong, or is there a bug in the example code?

**Comment by tikue** [comment]
Thanks for the report! That's interesting — I can't reproduce this problem on my Macbook, but I can't say you're doing anything wrong either! At least, not without a bit more info :)

- What's the specific error you're getting? Is it something like `invalid IP address syntax`?
- Can you try `--server-addr '[::1]:59061'`?

**Comment by ha-sante** [comment]
Same experience on end. Would add using the tarpc module feels like working in the dark as there is no logs you can tap into.

- Documentation can be incredibly better for launching a tcp transport server.
- Logs can be better for the dev experience.
- Example service doesn't tell you anything on fresh launch(execute client bin and it dosen't get a response log).

Still exploring for my use case and haven't managed to make an RPC call for 2 days now with pure pull from the example service.

Sorry.


Will contribute to making things better when am able to successfully make use of it and it's associated features. - A big blocker to contributions.
Sorry.

**Comment by tikue** [comment]
Hi, I'm sorry you've had a frustrating experience! Feel free to join the discord channel where others might help fix your problems faster.

There should be some logs available for the client binary, not sure what's going wrong.  Have you enabled log output with RUST_LOG environment variable? E.g. `RUST_LOG=debug cargo run --bin client`?

**Comment by ha-sante** [comment]
F##k yeah, it finally logged. Your command did it.

Would this be my knowledge of rust or it's how you get debug information from your setup?

_- I learned rust fully a few days ago hence my curiosity_

Most helpful thing I will do now is to write a beginners guide once am up to speed with what am doing.

**Comment by tikue** [comment]
Nice! RUST_LOG is not specific to tarpc, but it would still be good for the examples that use it to specify how to get output :)

**Comment by ha-sante** [comment]
Can see, my memory bank needs an update. Thanks for the insight.
