### ISSUE TITLE
Server acting as a client to another server

### ISSUE THREAD

**Issue by jimouris** [google/tarpc#383]
Hi, I'm trying to make a server act as a client to another server when the `async` function for the service is getting called.

I'm looking at the [custom_transport.rs](https://github.com/google/tarpc/blob/0e102288a5da76b517ba698c3cd57a81f4e44757/tarpc/examples/custom_transport.rs) example below and I want the server to act as a client to another server when the `ping` function is invoked:

```rust
#[tarpc::service]
pub trait PingService {
    async fn ping();
}

#[derive(Clone)]
struct Service;

#[tarpc::server]
impl PingService for Service {
    async fn ping(self, _: Context) {
    // Can I connect to a new server here?
    }
}
```

I'm running into the following error when I put the `client` code inside the above `ping` function:
```
#[tarpc::server]
    | ^^^^^^^^^^^^^^^^ future created by async block is not `Send`
```

I just started working with `tarpc` so I might be missing something basic. Any help is appreciated!

**Comment by tikue** [comment]
Hi! I think the [pubsub](https://github.com/google/tarpc/blob/master/tarpc/examples/pubsub.rs) example does something like this: see [`async fn publish`](https://github.com/google/tarpc/blob/master/tarpc/examples/pubsub.rs#L262)

I'd also be happy to take a look at your code, if you can point me to it!

**Comment by jimouris** [comment]
Thanks! Let me take a look at the publish function first and I'll get back to you.

**Comment by jimouris** [comment]
Hi @tikue, I have another similar question. I have declared my functions similarly to (readme.rs)[https://github.com/google/tarpc/blob/master/tarpc/examples/readme.rs#L31] where in the `trait` they are declared as `async` but in the implementation, they are not. When I put the `async` keyword in the implementation (like line 31 in front of `fn hello(...`) I get the following error:
```
expected struct `futures::future::Ready`, found opaque type`
```

The "opaque type" is `Ready<String>`.

**Comment by jimouris** [comment]
Okay, I think I figured it out. So, after adding the `#[tarpc::server]` and the `async` keyword, I had to completely remove the Futures. Now it works fine. Does the `#[tarpc::server]` automatically translate the return types to futures?

**Comment by tikue** [comment]
Ah, yes, that is correct! `#[tarpc::server]` is an optional attribute that hides some of the boilerplate of defining the Future associated types and such.
