### ISSUE TITLE
On `poll_flush` timing of RPC client and server

### ISSUE THREAD

**Issue by 0x5459** [google/tarpc#384]
Hi, 

Big fan of this repo. 

I found that each time a write request to transport in RPC client, the [poll_flush](https://github.com/google/tarpc/blob/0c08d5e8cabe8ac5d9f1f01ed76c5ba69ada7339/tarpc/src/client.rs#L490) method will be called by the `pump_write` of `RequestDispatch`. This approach may not be cache friendly. I wrote a quick [demo](https://github.com/0x5459/ext-proc-channel/blob/85a8f275d0e0ff3e517d1a96bef5ab3ac27a89e4/src/client.rs#L253) using `start_send` in a loop to mimic multiple requests and then [pull_flush](https://github.com/0x5459/ext-proc-channel/blob/85a8f275d0e0ff3e517d1a96bef5ab3ac27a89e4/src/client.rs#L228) all these requests in one try.

In my demo, `pump_write` no longer writes one request at a time but it's writing requests all the time. Same with `pump_read`. If you think this is the right approach, I'm more than happy to submit a PR for this.

**Comment by tikue** [comment]
Hi! Thanks for the kind words 😊

Thank you for pointing this out! I think it's a great suggestion to flush less frequently. Please send a PR!

**Comment by tikue** [comment]
Looking more closely, I think this is the problem line: https://github.com/0x5459/ext-proc-channel/blob/85a8f275d0e0ff3e517d1a96bef5ab3ac27a89e4/src/client.rs#L269

`start_send` returns an Err when the write buffer is full, which means we need to flush, right?

**Comment by 0x5459** [comment]
https://github.com/0x5459/ext-proc-channel/blob/85a8f275d0e0ff3e517d1a96bef5ab3ac27a89e4/src/client.rs#L232

**Comment by 0x5459** [comment]
> Looking more closely, I think this is the problem line: https://github.com/0x5459/ext-proc-channel/blob/85a8f275d0e0ff3e517d1a96bef5ab3ac27a89e4/src/client.rs#L269 because it doesn't check if the transport is ready for a request to be buffered.
> 
> `start_send` returns an Err when the write buffer is full, which means we need to flush, right? Otherwise the channel could spuriously fail.
> 
> The ensure_writeable fn doesn't always flush; it tries to only flush when the transport's buffer is full.

I'm sorry. You're right. Great code!
