### ISSUE TITLE
Removing the dependency on tokio

### ISSUE THREAD

**Issue by axos88** [google/tarpc#387]
Great stuff!

My intention is to use this library in embedded projects where every byte of memory usage counts. The intention is to set up a reverse rpc so that units scattered behind nats could connect to a gateways, and be made accessible over the internet through that.

The environment (esp-rs) has built in support for smol, i guess because of its small resource footprint. It is possible to spin up a tokio loop within smol, but due to the constricted resources I would like to avoid that. 

Reading through the issues it seems there is no hard dependency on tokio except timers and channels.

How hard do you think it would be to abstract these away and provide integration with both tokio and smol / async_std depending on activated features?

**Comment by tikue** [comment]
Thanks for filing this! I would definitely be supportive of updating dependencies to facilitate running on esp-rs. Channels should be pretty easy to replace. I don't know offhand how difficult it would be to abstract away timers, though. Are there any alternatives that provide the functionality needed? As mentioned in #385, it's not clear how to abstract away `DelayQueue`. Maybe it would just need to be removed; the code would need some significant refactoring to remove it.

I'm happy to explore this further, but I probably can't take the lead on it any time soon. If you want to look into it further, I'd be happy to review any work-in-progress PRs after the holidays.

**Comment by axos88** [comment]
Hmmm. It seems to me that delayqueue could be replaced by a bunch of ``` ::spawn async { sleep(duration).await; do_thing.await }```. Rescheduling is a bit tricky, but I'd say not impossible. We are using a LUT keyed by the request is anyway, the values could be the task handles returned by spawn to enable cancellation, and rescheduling is basically a cancellation and a scheduling with the new timeout. Although I'm not sure if rescheduling is really needed in terms of tarpc. Not as nice as having them in a stream, but it should work. Or it could also be implemented for smol is guess.

Not sure about performance of this though.

**Comment by axos88** [comment]
Closing in favor of #385
