### ISSUE TITLE
use qualified paths for all macro generated signatures 

### ISSUE THREAD

**Issue by chaoky** [google/tarpc#390]
I stumbled upon this when defining my Api's result type, 
not prefixing the module's name is a Rust convention ie. `module::Result` instead of `module::ModuleResult`.

is there a reason to not use qualified paths in the generated code?

```Rust 
type Result<T> = std::result::Result<T, Error>;

#[tarpc::service]
pub trait Api {
    async fn active_tables() -> Result<Vec<Instance>>;
    async fn all_tables(from: usize, to: usize) -> Result<Vec<Instance>>;
    async fn update_table(new_table: Instance) -> Result<()>;
}

#[derive(Error, Debug, Serialize, Deserialize)]
pub enum Error {
    ...
}
```

**Comment by tikue** [comment]
Hi, sorry for not responding last year! There was no reason other than laziness! And as of https://github.com/google/tarpc/pull/417, it should be fixed :)
