### ISSUE TITLE
Multi-client requests

### ISSUE THREAD

**Issue by rsalmei** [google/tarpc#394]
Hi! 

Similar to #268, I also need to manage several client connections at the same time, but instead of load balancing them, I'll be calling them all with something like [futures_util::join_all](https://docs.rs/futures-util/latest/futures_util/future/fn.join_all.html) (on a LAN), merging their responses together with their names, and responding the call with this "enriched" answer.

So, if I had:
```rust
trait Doctor {
    async fn get_specialties() -> Vec<String>;
}
```

I'd need:
```rust
trait Doctors {
    async fn get_specialties() -> Vec<(String, Vec<String>)>;
}
```

How would I handle errors in this scenario? And timeouts, returning only the answers I could get in time?
Any tips/concerns on making this happen?
Thank you!

**Comment by tikue** [comment]
Hi! Sorry for not responding last year. For something like this, I think the Doctors service implementation would be able to implement everything you said pretty straightforwardly: send out N requests with whatever deadline will allow the service to respond in time; iterate over the responses, filtering out any deadline-exceeded errors; and then return the result?

If you're still interested in this and struggling to implement something, feel free to share a link to your work in progress, and I'll try to take a look.

**Comment by rsalmei** [comment]
Hey, don't worry, thanks.
I'd forgotten this was still open, `join_all` worked nicely! I can call a single device or multiple ones on demand.
Thank you.
