### ISSUE TITLE
Bidirectional RPC

### ISSUE THREAD

**Issue by rsalmei** [google/tarpc#395]
Hey!

Please, is it possible to both serve a service _and_ consume a service on the other side, on the same TCP transport? I mean, both the client (initiator of the connection) and the server consuming a service on a full-duplex TCP connection?

Thanks!

**Comment by tikue** [comment]
Hi, thanks for the question! Yes, this is possible. There was a similar question, with some example code, on https://github.com/google/tarpc/issues/300.

**Comment by rsalmei** [comment]
Awesome, thank you @tikue!

**Comment by tikue** [comment]
You're welcome :) closing this now, but feel free to reopen later if you want!
