### ISSUE TITLE
Cross Platform Procedure Call

### ISSUE THREAD

**Issue by paulocoutinhox** [google/tarpc#396]
Hi,

I have a project called XPLPC (https://github.com/xplpc/xplpc) that has same nice features and support most used plataforms.

But i don't have rust support.

Can someone add Rust support there?

Thanks.

**Comment by tikue** [comment]
Hi! I'm confused, are you looking for a feature to be added to tarpc?

**Comment by tikue** [comment]
Closing this but please reopen if you still think tarpc could help with your use case. Thanks!
