### ISSUE TITLE
[FEATURE REQUEST] Stream responses

### ISSUE THREAD

**Issue by axos88** [google/tarpc#397]
Probably not a simple addition to the library, but I would love to see the ability to respond with a stream of data, instead of a one-off future.
Some careful thought needs to be made as to how when the stream should be closed on the server side, since dropping the Stream on the client side should okay-ish to propagate using the same guard semantics as we are with the futures, but the receiving end may disappear ungracefully, and the server side would need to know to stop producing the values at one point or another. (Some form of keepalive, or a way for the poll calls to cross the RPC boundary?)

**Comment by axos88** [comment]
I am referring to something like "I'd like to be notified to changes of this value".

**Comment by tikue** [comment]
Hi, thanks for the feature request! As a workaround, could you use a bi-directional transport (like the one I describe in #300) that allows both client and server to each host a service? The client opens the connection, and then the client and server both use that connection to initialize a service. The client can send an RPC informing the server of the events it cares about. Then, the server can send a new RPC to the client over the client-side service when the event occurs.

**Comment by axos88** [comment]
Yeah I mean that seems like a plausible workaround, I'll need to think how I can apply this to my use case, but it should be doable. Of course it would be best if it would be supported out of the box :)

**Comment by tikue** [comment]
Due to the inherent complexities, I don't think streaming is a good fit for tarpc. I'm going to close this issue, but if you think I've missed something, please feel free to reopen. Thanks!
