### ISSUE TITLE
Document why services have to be `Clone`

### ISSUE THREAD

**Issue by shaladdle** [google/tarpc#64]
Right now services must be `Clone`, but it's not obvious (imho at least) *why* they are clone. Users might make incorrect assumptions about what mutating their service object within a service implementation does. They might think they're modifying the one copy of the struct, while really they're just modifying a clone.

```rust
struct MyServer {
  counter: u64,
}

impl Service for MyServer {
  fn do_thing(&mut self) {
    self.counter += 1; // Only ever increments the copy that is made by the tarpc layer :(
}
```

**Comment by tikue** [comment]
Closing as dup of #57 which already has a note about `Clone`. Feel free to flesh out that issue a bit more.
