### ISSUE TITLE
Clean up crate structure

### ISSUE THREAD

**Issue by tikue** [google/tarpc#66]
- Which modules should be public?
- Which types should be reexported from the crate root?
- Which types must be public but should be hidden from documentation?
- Which types are currently public but shouldn't be? e.g. `client::Either`, `__tarpc_service_Request`, etc.

**Comment by compressed** [comment]
I was also wondering if it's a good idea to keep all these crates hidden?

```rust
#[doc(hidden)]
pub extern crate bincode;
#[doc(hidden)]
pub extern crate futures;
#[doc(hidden)]
pub extern crate serde;
#[doc(hidden)]
pub extern crate tokio_core;
#[doc(hidden)]
pub extern crate tokio_proto;
#[doc(hidden)]
pub extern crate tokio_service;
```

Because, for instance, in the README (for futures), it implies you need to add `futures` and `tokio_core` crates to your own package, when really you could just do:

```rust
use tarpc::futures::Future;
use tarpc::tokio_core::reactor;
```

I don't see any harm in exposing these.

**Comment by tikue** [comment]
I think it's typically not considered idiomatic to publicly export dependencies. The only reason I do it here is because it's the only way to guarantee that the macro-generated code compiles (I wouldn't want to rely on users having all the required `extern crate`s).

**Comment by tikue** [comment]
To add to that, if macros ever gain a way to use crates not publicly externed by its own crate, then I wouldn't want it to be a breaking change to change the current public crates to private (I'm pretty sure semver is ok with removing a public-but-hidden item).
