### ISSUE TITLE
Feature:  SSL/TLS Support

### ISSUE THREAD

**Issue by rohitjoshi** [google/tarpc#77]
Any plans to add support for SSL/TLS?

**Comment by tikue** [comment]
Yes! @compressed is working on it, I believe. Unfortunately I caused https://github.com/tikue/tarpc/pull/7 to bitrot, but hopefully it'll be ready soon!

**Comment by rohitjoshi** [comment]
👍

**Comment by compressed** [comment]
Yup. I should have a new PR this week!

**Comment by rohitjoshi** [comment]
Thanks.  Does it support mutual SSL where client can be verified using SSL CN?
