### ISSUE TITLE
Feature: generic serializers

### ISSUE THREAD

**Issue by tikue** [google/tarpc#83]
Currently we hardcode bincode. If we support generic serializers then bincode should become a default feature so it can be disabled.

**Comment by tikue** [comment]
`tarpc::Error` would either need to become generic over two error types, application and serialization errors, or we could just make the serialize error variant store a string. Would that be awful?

**Comment by kyegupov** [comment]
How about an even wilder idea: generic _transport_? Imagine using tarpc codegen to build HTTP REST services, emulating the functionality of Jersey and Feign. 

That would mean, of course, building some equivalent of JAX-RS annotations, which is another can of worms...

**Comment by tikue** [comment]
I think that's covered by #38. A long time ago, when I first started tarpc, the transport actually was generic. But I felt usability suffered. Could be worth revisiting if the landscape is different now!

**Comment by tikue** [comment]
Obsoleted by #199.
