### ISSUE TITLE
Investigate `Clone` requirement on `FutureService`

### ISSUE THREAD

**Issue by tikue** [google/tarpc#86]
Potentially replace this with something like tokio's `NewService` trait.

cc @jonhoo

**Comment by tikue** [comment]
Or just wrap future services in `Rc`

**Comment by compressed** [comment]
In one case I ran into today I needed to use run some things in a `CpuPool` so my service actually needs to be in an `Arc`. I'm not sure if implicitly wrapping in `Rc` is a good idea.

**Comment by tikue** [comment]
Yeah, I just ran into a similar case where I needed to modify state in a future transformation, which requires wrapping the state in an `Rc<RefCell<>>`. In that case there's really not much benefit to doing this for the user.

**Comment by tikue** [comment]
Closing this for now. I don't think there's enough benefit in doing it for the user because most state is managed in future transform closures, not the root rpc fn.
