### ISSUE TITLE
Document that with default options, all clients share single event loop

### ISSUE THREAD

**Issue by jonhoo** [google/tarpc#88]
`Options::default()` sets `Options.reactor = None`, which causes `Client::connect` to use [`REMOTE.spawn`](https://github.com/google/tarpc/blob/master/src/client.rs#L345). To my great surprise, `REMOTE` is a [static](https://github.com/google/tarpc/blob/master/src/lib.rs#L168) event loop driven by [a single thread](https://github.com/google/tarpc/blob/master/src/lib.rs#L176). Thus, if `Options::default()` is used, all RPC calls block on a single thread. This should be clearly documented, as that thread will quickly become a big bottleneck for high performance systems.

**Comment by tikue** [comment]
Default options are going away (because defaulting to a `Remote` requires services to be `Send` when they shouldn't have to be), so this shouldn't be an issue in the future.
