### ISSUE TITLE
Change SyncService::listen to block forever

### ISSUE THREAD

**Issue by tikue** [google/tarpc#90]
This removes a potential footgun of blocking the thread driving the sync server. It also requires changing `listen` to take a `SocketAddr` rather than `A: ToSocketAddrs`, since we can't return an address anymore.

cc @jonhoo @shaladdle

**Comment by tikue** [comment]
I actually don't think there's any need to do this. I think changing `SyncClient` should be sufficient.

**Comment by jonhoo** [comment]
@tikue As you pointed out yesterday, it does open up the possibility of users accidentally getting into a deadlock, but maybe that's fine? Personally, I was expecting `listen` to be `-> !` the first time I used it, or at least to return a future that never resolves, but I don't think it's terribly important.

**Comment by tikue** [comment]
I think the listen and connect are both broken right now if you pass in a handle, because that means they'll block the thread with the reactor. I think both sync and future services can be changed to return () so that there's no blocking/future component in the setup.
